### ISSUE TITLE
Union multiple sorted sets with top K elements returned

### ISSUE THREAD

**Issue by levyfan** [RedisLabsModules/redex#2]
See details:
https://groups.google.com/forum/#!topic/redis-dev/gTX6Jt2gr3s

Proposed command:
ZUNIONMINK k numkeys key [key ...] [WEIGHTS weight [weight ...]] [WITHSCORES]
ZUNIONMAXK k numkeys key [key ...] [WEIGHTS weight [weight ...]] [WITHSCORES]

**Comment by itamarhaber** [comment]
Closed by #3
